### ISSUE TITLE
MyFreeCams Plugin failed loading

### ISSUE THREAD

**Issue by ZwiebelTVDE** [Damianonymous/streamlink-plugins#21]
I just found your plugins and wanted to try to record something from myfreecams.com

when launching the command I got the following ouput:
```root@StreamFarmer:~/test# streamlink https://www.myfreecams.com/VivianWest best --loglevel debug -o mfc.mp4
[session][error] Failed to load plugin myfreecams from /root/.config/streamlink/plugins
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/streamlink/session.py", line 423, in load_plugins
    mod = load_module(module_name, path)
  File "/usr/lib/python3/dist-packages/streamlink/utils/__init__.py", line 25, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.config/streamlink/plugins/myfreecams.py", line 6, in <module>
    from streamlink.compat import unquote
ImportError: cannot import name 'unquote' from 'streamlink.compat' (/usr/lib/python3/dist-packages/streamlink/compat.py)
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.11.22-4-pve-x86_64-with-debian-10.11
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.53.0)
error: No plugin can handle URL: https://www.myfreecams.com/VivianWest
```

Is the error on my side or is the plugin broken right now?
I think some time ago streamlink changes something on how the plugins behave so maybe its just not updated yet?

**Comment by Damianonymous** [comment]
Yes, it's the fault of the next Streamlink updates. For nsfw plugins, I'm using version 1.0.0.
